### PR TITLE
Intro, Understanding & Context, and Migrations Draft 1

### PR DESCRIPTION
**Pull request by EARnagram**
I think I may have repeated myself a bit and I'm pulling a lot from the Rails Tutorial from Michal Holy Sweetness Hartl.

Lemme know what needs to be improved!

### CODE REVIEW

**Comment by h4w5** [comment]
Alright. Checking out.

**Comment by EARnagram** [comment]
Heyo, 
1:n relationship is ready

ezRAez

**Comment by EARnagram** [comment]
Everything's ready! Gimme that collaborator access!

**Comment by h4w5** [comment]
@EARnagram did this clear out issue #4?

**Pull request merged**
